repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: hashicorp
  url: https://helm.releases.hashicorp.com

releases:
- name: kps
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  atomic: true
  cleanupOnFail: true
- name: argocd
  namespace: argo
  chart: argo/argo-cd
  atomic: true
  cleanupOnFail: true
- name: vault
  namespace: security
  chart: hashicorp/vault
  atomic: true
  cleanupOnFail: true