# https://taskfile.dev

version: '3'

vars:
  CLUSTER_NAME: homestyle

tasks:

  up:
    desc: "ensure helm readiness, create cluster, install releases"
    cmds:
      - task: hfs
      - task: cu
      - task: hfu
    silent: true

  cluster_up:
    desc: "create the cluster"
    aliases:
      - cu
    cmds:
      - kind create cluster -n "{{.CLUSTER_NAME}}" --config kind-config.yaml
    silent: true

  cluster_down:
    desc: "delete the cluster"
    aliases:
      - cd
    cmds:
      - kind delete cluster -n "{{.CLUSTER_NAME}}"
    silent: true

  helmfile_setup:
    desc: "ensure that helmfile is setup"
    aliases:
      - hfs
    cmds:
      - helmfile init
      - helmfile deps

  helmfile_up:
    desc: "create releases from the specified helm charts"
    aliases:
      - hfu
    cmds:
      - helmfile sync
    silent: true

  helmfile_down:
    desc: "uninstall all helm releases"
    aliases:
      - hfd
    cmds:
      - helmfile destroy